### ISSUE TITLE
Add tests for trigger sync and adapter's handler

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/knative-sources#37]
Zendesk source needs tests.

- [x] ~Zendesk controller~ (#116)
- [ ] Mini zendesk client at the controller
- [ ] Zendesk adapter's handler

**Comment by antoineco** [comment]
@odacremolbap this issue was created over a year ago. Since we have a more general problem that a few source adapters aren't well tested, what would you say about closing this and revisiting the "testing" topic after the repo has been migrated?

**Comment by odacremolbap** [comment]
sure thing!
