### ISSUE TITLE
Scale the documentation Image sizes down that were added for the Zendesk Source. 

### ISSUE THREAD

**Issue by JeffNaef-Triggermesh** [triggermesh/knative-sources#40]

**Comment by antoineco** [comment]
Worth merging with https://github.com/triggermesh/docs/pull/21

**Comment by JeffNaef-Triggermesh** [comment]
@antoineco @odacremolbap can this be considered resolved? If not is there a maximum size that I should adjust to? They appear to be the same size as other images in the repository.

**Comment by JeffNaef-Triggermesh** [comment]
well actually.. this can def be closed bc @antoineco removed them from this repo 😂
