### ISSUE TITLE
Zendesk: Create coherent set of event types

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-sources#45]
There are multiple problems with the current Zendesk source.

1. Adapter sends events of type `com.zendesk.ticket`, but we already discussed those types should be more specific, e.g. : `com.zendesk.ticket.created`/`com.zendesk.ticket.deleted`/`com.zendesk.ticket.updated`. Apparently those comments were ignored in the original PR.

1. Controller declares that the event types emitted by the source are of type `com.zendesk.events`, which is not aligned with the code from the adapter, and wrong due to `1.`.

**Comment by JeffNaef-Triggermesh** [comment]
ok no problem!

**Comment by JeffNaef-Triggermesh** [comment]
also! Apologies for missing this comment in the first PR!
